service: upload
frameworkVersion: '3'

provider:
  name: aws
  runtime: nodejs18.x

# some variables
some:
  s3:
    bucket: leaf3bbilguunbucket

# --

resources:
  Resources:
    S3Bucket:
      Type: AWS::S3::Bucket
      Properties:
        BucketName: ${self:some.s3.bucket}
        CorsConfiguration:
          CorsRules:
            - AllowedHeaders:
                - '*'
              AllowedMethods:
                - PUT
                - GET
                - DELETE
              AllowedOrigins:
                - '*'
    BucketPolicy:
      Type: AWS::S3::BucketPolicy
      Properties:
        Bucket: !Ref S3Bucket
        PolicyDocument:
          Statement:
            - Action:
                - s3:ListBucket
                - s3:GetObject
                - s3:PutObject
                - s3:DeleteObject
              Resource:
                - arn:aws:s3:::${self:some.s3.bucket}/*
                - arn:aws:s3:::${self:some.s3.bucket}
              Effect: Allow
              Principal: '*'

functions:
  createApproachUrl:
    handler: handlers/createApproachUrl.handler
    events:
      - http:
          path: url
          method: post
          cors: true
